from qt_compat import QGridLayout, QGroupBox, QHBoxLayout, QLabel, QLineEdit, QPushButton, QVBoxLayout, QWidget


class CalibrationTab(QWidget):
    def __init__(self):
        super().__init__()
        self.calibrate = QPushButton("Leader 校准终端")
        self.use_existing = QPushButton("写入已有 Leader 校准")
        self.scan_left_leader = QPushButton("扫描左 Leader")
        self.scan_right_leader = QPushButton("扫描右 Leader")
        self.left_serial = QLineEdit()
        self.left_serial.setPlaceholderText("左 Leader USB serial")
        self.right_serial = QLineEdit()
        self.right_serial.setPlaceholderText("右 Leader USB serial")
        self.apply_leader_mapping = QPushButton("应用 Leader 映射")
        self.verify_leader_mapping = QPushButton("验证 Leader 映射")
        self.check_pi_followers = QPushButton("检查 Pi Follower")
        self.left_follower_id = QLineEdit("follower_arm_left")
        self.left_follower_id.setPlaceholderText("左 Follower 校准 ID")
        self.right_follower_id = QLineEdit("follower_arm_right")
        self.right_follower_id.setPlaceholderText("右 Follower 校准 ID")
        self.follower_profile = QLineEdit("am-follower-6dof-hd")
        self.follower_profile.setPlaceholderText("Follower arm_profile")
        self.calibrate_left_follower = QPushButton("左 Follower 校准")
        self.calibrate_right_follower = QPushButton("右 Follower 校准")
        self.next_step = QLabel("下一步：扫描 Leader serial，填写后应用映射。")
        self.next_step.setObjectName("diagnosticStatus")
        self.next_step.setWordWrap(True)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(10, 8, 10, 10)
        layout.setSpacing(10)

        mapping_box = QGroupBox("端口映射")
        mapping_layout = QVBoxLayout(mapping_box)
        mapping_layout.setContentsMargins(12, 8, 12, 10)
        mapping_layout.setSpacing(8)

        grid = QGridLayout()
        grid.setHorizontalSpacing(8)
        grid.setVerticalSpacing(6)
        grid.addWidget(QLabel("左 Leader"), 0, 0)
        grid.addWidget(self.left_serial, 0, 1)
        grid.addWidget(self.scan_left_leader, 0, 2)
        grid.addWidget(QLabel("右 Leader"), 1, 0)
        grid.addWidget(self.right_serial, 1, 1)
        grid.addWidget(self.scan_right_leader, 1, 2)
        mapping_layout.addLayout(grid)
        mapping_actions = QHBoxLayout()
        mapping_actions.addWidget(self.apply_leader_mapping)
        mapping_actions.addWidget(self.verify_leader_mapping)
        mapping_actions.addWidget(self.check_pi_followers)
        mapping_layout.addLayout(mapping_actions)
        layout.addWidget(mapping_box)

        leader_box = QGroupBox("Leader 校准")
        leader_layout = QVBoxLayout(leader_box)
        leader_layout.setContentsMargins(12, 8, 12, 10)
        leader_layout.setSpacing(8)
        leader_actions = QHBoxLayout()
        leader_actions.addWidget(self.calibrate)
        leader_actions.addWidget(self.use_existing)
        leader_layout.addLayout(leader_actions)
        layout.addWidget(leader_box)

        follower_box = QGroupBox("Follower 校准")
        follower_layout = QVBoxLayout(follower_box)
        follower_layout.setContentsMargins(12, 8, 12, 10)
        follower_layout.setSpacing(8)

        follower_grid = QGridLayout()
        follower_grid.setHorizontalSpacing(8)
        follower_grid.setVerticalSpacing(6)
        follower_grid.addWidget(QLabel("左 Follower ID"), 0, 0)
        follower_grid.addWidget(self.left_follower_id, 0, 1)
        follower_grid.addWidget(self.calibrate_left_follower, 0, 2)
        follower_grid.addWidget(QLabel("右 Follower ID"), 1, 0)
        follower_grid.addWidget(self.right_follower_id, 1, 1)
        follower_grid.addWidget(self.calibrate_right_follower, 1, 2)
        follower_grid.addWidget(QLabel("arm_profile"), 2, 0)
        follower_grid.addWidget(self.follower_profile, 2, 1, 1, 2)
        follower_layout.addLayout(follower_grid)
        layout.addWidget(follower_box)
        layout.addWidget(self.next_step)

        layout.addStretch(1)

    def set_next_step(self, text: str) -> None:
        self.next_step.setText(f"下一步：{text}")
